# Generated by Django 5.0.9 on 2024-09-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='custom_gender',
        ),
    ]
