# Generated by Django 5.0.6 on 2024-08-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='is_custom',
        ),
    ]
