# Generated by Django 5.0.6 on 2024-07-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergoal',
            old_name='predefined_goal',
            new_name='goal_title',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='predefined_role',
            new_name='role_title',
        ),
    ]
