# Generated by Django 5.0.6 on 2024-07-19 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('Personal', 'Personal'), ('Professional', 'Professional')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='role',
            old_name='custom_role_name',
            new_name='custom_title',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='roles',
            new_name='role',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('title', 'group')},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.ManyToManyField(related_name='user_profiles', to='user_management.goal'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_group',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
    ]
