# Generated by Django 5.0.6 on 2024-08-28 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_sphere', '0003_alter_area_life_sphere'),
        ('user_management', '0002_alter_userarea_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('life_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_balances', to='life_sphere.lifesphere')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
