# Generated by Django 5.0.6 on 2024-07-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_goal_rename_custom_role_name_role_custom_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(max_length=20),
        ),
    ]
