# Generated by Django 5.0.6 on 2024-07-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rename_predefined_goal_usergoal_goal_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='user_management.usergoal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='user_management.userrole'),
        ),
    ]
