# Generated by Django 5.0.6 on 2024-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.ManyToManyField(blank=True, null=True, to='user_management.usergoal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='user_management.userrole'),
        ),
    ]
