# Generated by Django 5.0.6 on 2024-08-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_role_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('Professional Roles', 'Professional Roles'), ('Personal Roles', 'Personal Roles'), ('Self-Improvement Roles', 'Self-Improvement Roles'), ('Community and Social Impact Roles', 'Community and Social Impact Roles'), ('Wellness and Spiritual Roles', 'Wellness and Spiritual Roles')], default='none', max_length=50),
            preserve_default=False,
        ),
    ]
