# Generated by Django 5.0.6 on 2024-07-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_usergoal_user_remove_userrole_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingstep',
            name='step_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goals',
            field=models.ManyToManyField(blank=True, to='user_management.usergoal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='user_management.userrole'),
        ),
    ]
