# Generated by Django 5.0.6 on 2024-07-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_userprofile_goals_alter_userprofile_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='role_title',
            new_name='predefined_role',
        ),
    ]
