# Generated by Django 5.0.6 on 2024-08-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_userbalance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userarea",
            name="custom_area",
        ),
        migrations.RemoveField(
            model_name="userarea",
            name="is_custom",
        ),
    ]
