# Generated by Django 5.0.9 on 2024-09-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say'), ('Non-binary', 'Non-binary'), ('Self describe', 'Prefer to self-describe')], max_length=20),
        ),
    ]
