# Generated by Django 5.0.6 on 2024-07-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_onboardingstep_step_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ai_assistant_model',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('friend', 'Friend'), ('coach', 'Coach'), ('therapist', 'Therapist')], max_length=255),
        ),
    ]
