# Generated by Django 5.0.6 on 2024-07-25 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_rename_role_title_userrole_predefined_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='predefined_role',
            new_name='title',
        ),
    ]
