# Generated by Django 5.0.6 on 2024-08-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
