# Generated by Django 5.0.6 on 2024-08-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_userrole_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user_profiles',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_profile',
            field=models.ManyToManyField(related_name='user_role', to='user_management.userprofile'),
        ),
    ]
