# Generated by Django 5.0.6 on 2024-07-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_rename_predefined_role_userrole_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='title',
            new_name='role',
        ),
    ]
