# Generated by Django 5.0.6 on 2024-07-24 15:19

import user_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_userprofile_ai_assistant_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/', validators=[user_management.validators.validate_profile_image]),
        ),
    ]
