# Generated by Django 5.0.9 on 2024-09-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_rename_profile_picture_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
