# Generated by Django 5.0.6 on 2024-08-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0005_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbalance",
            name="user",
        ),
        migrations.AddField(
            model_name="userbalance",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="user_management.userprofile",
            ),
        ),
    ]
