# Generated by Django 5.0.6 on 2024-08-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0006_remove_userrole_user_profiles_userrole_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_profiles',
            field=models.ManyToManyField(related_name='user_role', to='user_management.userprofile'),
        ),
    ]
