# Generated by Django 5.0.6 on 2024-07-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_rename_title_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
