# Generated by Django 5.0.9 on 2024-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_userprofileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileimage',
            name='test_field',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
    ]
