# Generated by Django 5.0.6 on 2024-07-29 17:46

import user_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='empty', upload_to='profile_picture/', validators=[user_management.validators.validate_profile_image]),
            preserve_default=False,
        ),
    ]
