# Generated by Django 5.0.6 on 2024-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0007_remove_userrole_user_profile_userrole_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_profiles',
            field=models.ManyToManyField(related_name='user_roles', to='user_management.userprofile'),
        ),
    ]
