# Generated by Django 5.0.6 on 2024-08-01 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0008_alter_userrole_user_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='custom_group',
            new_name='group_name',
        ),
    ]
