# Generated by Django 5.0.9 on 2024-09-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_userprofileimage_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileimage',
            name='test_field',
        ),
    ]
