# Generated by Django 5.0.6 on 2024-07-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='custom_title',
            new_name='custom_role',
        ),
    ]
