# Generated by Django 5.0.6 on 2024-08-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0009_rename_custom_group_userrole_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
