# Generated by Django 5.0.9 on 2024-09-24 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_remove_userprofileimage_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile'),
        ),
    ]
