# Generated by Django 5.0.9 on 2024-09-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_userprofileimage_user_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofileimage',
            unique_together={('user_profile', 'profile_image')},
        ),
    ]
