# Generated by Django 5.0.7 on 2024-08-04 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_usergoal_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='progress',
            field=models.FloatField(default=0.0, help_text='Progress in percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
