# Generated by Django 5.0.9 on 2024-09-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0010_alter_userprofile_birth_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserHabit",
        ),
    ]
