# Generated by Django 5.0.6 on 2024-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='custom_role',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
