# Generated by Django 5.0.6 on 2024-08-07 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_management', '0001_initial'),
        ('user_management', '0012_userhabit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhabit',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission_statement', models.TextField(blank=True, null=True)),
                ('tailored_by_ai', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_mission', to='user_management.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_principle', models.CharField(blank=True, max_length=255, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('principle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principle_management.principle')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_principles', to='user_management.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userprinciple',
            constraint=models.UniqueConstraint(fields=('user_profile', 'principle'), name='unique_user_principle'),
        ),
        migrations.AddConstraint(
            model_name='userprinciple',
            constraint=models.UniqueConstraint(fields=('user_profile', 'custom_principle'), name='unique_user_custom_principle'),
        ),
    ]
