# Generated by Django 5.0.9 on 2024-09-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_alter_userprofileimage_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
