# Generated by Django 5.0.6 on 2024-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0013_userhabit_is_custom_userrole_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='goal_type',
            field=models.CharField(choices=[('short_term', 'Short-term'), ('long_term', 'Long-term')],
                                   default='not predefined'),
        ),
    ]
