# Generated by Django 5.0.9 on 2024-10-02 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
