# Generated by Django 5.0.6 on 2024-08-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_alter_usergoal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
