# Generated by Django 5.0.6 on 2024-08-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0016_alter_usergoal_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='goal_type',
            field=models.CharField(choices=[('short_term', 'Short-term'), ('long_term', 'Long-term')]),
        ),
    ]
