# Generated by Django 5.0.9 on 2024-10-02 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_alter_userprofile_custom_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only letters and spaces.', regex='^[A-Za-z ]+$')]),
        ),
    ]
