# Generated by Django 5.0.9 on 2024-10-02 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_alter_userprofile_custom_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(code='invalid_gender', message='Custom gender must contain only letters and spaces.', regex='^[A-Za-z ]+$')]),
        ),
    ]
