# Generated by Django 5.0.9 on 2024-10-04 21:01

import user_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_alter_userprofile_custom_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_picture/', validators=[user_management.validators.validate_profile_image]),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user', 'profile_image')},
        ),
        migrations.DeleteModel(
            name='UserProfileImage',
        ),
    ]
