# Generated by Django 5.0.9 on 2024-10-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goal_task', '0003_initial'),
        ('user_management', '0021_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='goal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='goal_task.goal'),
        ),
    ]
