# Generated by Django 5.0.9 on 2024-10-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_alter_usergoal_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_assistant_model',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dashboard_customization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_preferences',
        ),
    ]
