# Generated by Django 5.0.6 on 2024-08-14 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_alter_usergoal_goal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user_profiles',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_profiles',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='user_management.userprofile'),
            preserve_default=False,
        ),
    ]
