# Generated by Django 5.0.9 on 2024-10-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_remove_userprofile_ai_assistant_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_range',
            field=models.IntegerField(choices=[(1, '13-17'), (2, '18-24'), (3, '25-34'), (4, '35-44'), (5, '45-54'), (6, '55-64'), (7, '65 and above'), (8, 'Prefer not to say')], default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say'), ('Self describe', 'Prefer to self-describe')], max_length=20),
        ),
    ]
