# Generated by Django 5.0.9 on 2024-10-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_alter_userprofile_age_range_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_range',
            field=models.IntegerField(blank=True, choices=[(1, '13-17'), (2, '18-24'), (3, '25-34'), (4, '35-44'), (5, '45-54'), (6, '55-64'), (7, '65 and above'), (8, 'Prefer not to say')], default=None),
        ),
    ]
