# Generated by Django 5.0.6 on 2024-08-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_remove_userrole_user_profiles_userrole_user_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user_profiles',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_profiles',
            field=models.ManyToManyField(related_name='user_roles', to='user_management.userprofile'),
        ),
    ]
