# Generated by Django 5.0.6 on 2024-08-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0012_alter_goal_title'),
        ('user_management', '0025_remove_userrole_user_profiles_userrole_user_profiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='Role',
        ),
    ]
