# Generated by Django 5.0.6 on 2024-08-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0026_rename_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_profiles',
            field=models.ManyToManyField(related_name='roles', to='user_management.userprofile'),
        ),
    ]
