# Generated by Django 5.0.6 on 2024-08-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0027_alter_role_user_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group_name',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('professional', 'Professional'),
                                                        ('personal', 'Personal'), ('health', 'Health'),
                                                        ('finance', 'Finance'), ('social', 'Social'),
                                                        ('spiritual', 'Spiritual')], max_length=50, null=True),
        ),
    ]
