# Generated by Django 5.0.6 on 2024-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0028_alter_role_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='group_name',
            field=models.CharField(blank=True, choices=[('Family', 'Family'), ('Professional', 'Professional'), ('Personal', 'Personal'), ('Health', 'Health'), ('Finance', 'Finance'), ('Social', 'Social'), ('Spiritual', 'Spiritual')], max_length=50, null=True),
        ),
    ]
