# Generated by Django 5.0.6 on 2024-08-14 23:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0029_alter_role_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, validators=[core.models.validate_start_due_date]),
        ),
    ]
