# Generated by Django 5.0.9 on 2024-10-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0029_alter_userprofile_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_range',
            field=models.IntegerField(null=True),
        ),
    ]
