# Generated by Django 5.0.6 on 2024-08-14 23:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0030_usergoal_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='due_date',
            field=models.DateField(blank=True, null=True, validators=[core.models.validate_start_due_date]),
        ),
    ]
