# Generated by Django 5.0.9 on 2024-10-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0030_alter_userprofile_age_range'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprinciple',
            name='unique_user_custom_principle',
        ),
        migrations.RemoveField(
            model_name='userprinciple',
            name='custom_principle',
        ),
        migrations.RemoveField(
            model_name='userprinciple',
            name='is_active',
        ),
    ]
