# Generated by Django 5.0.6 on 2024-08-16 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0031_alter_usergoal_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
