# Generated by Django 5.0.9 on 2024-10-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0031_remove_userprinciple_unique_user_custom_principle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprinciple',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='user_management.userprofile'),
        ),
    ]
