# Generated by Django 5.0.6 on 2024-08-19 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0010_rename_maincategorycompletion_categorycompletion_and_more'),
        ('user_management', '0032_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_management.category'),
        ),
    ]
