# Generated by Django 5.0.6 on 2024-08-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0033_role_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='group_name',
        ),
    ]
