# Generated by Django 5.0.6 on 2024-08-20 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0010_rename_maincategorycompletion_categorycompletion_and_more'),
        ('user_management', '0034_remove_role_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='category_management.category'),
        ),
    ]
