# Generated by Django 5.0.6 on 2024-08-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0035_alter_role_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='user_profiles',
            new_name='user_profile',
        ),
    ]
