# Generated by Django 5.0.6 on 2024-08-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0036_rename_user_profiles_role_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='custom_role',
            new_name='custom_title',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='title',
        ),
    ]
