# Generated by Django 5.0.6 on 2024-08-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0037_rename_custom_role_role_custom_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
