# Generated by Django 5.0.6 on 2024-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goal_task_management", "0001_initial"),
        ("life_sphere", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="category",
            field=models.ManyToManyField(
                related_name="goals", to="life_sphere.lifesphere"
            ),
        ),
    ]
