# Generated by Django 5.0.9 on 2024-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal_task_management', '0001_initial'),
        ('life_sphere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='area',
            field=models.ManyToManyField(related_name='goals', to='life_sphere.area'),
        ),
    ]
