# Generated by Django 5.0.6 on 2024-08-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0002_initial'),
        ('user_management', '0003_alter_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_source', models.CharField(max_length=255)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('user_feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goal_task_management.goal')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='user_management.userprofile')),
            ],
        ),
    ]
