# Generated by Django 5.0.6 on 2024-08-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0003_alter_subtask_completed_at_alter_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='impact_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_predefined',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
