# Generated by Django 5.0.6 on 2024-08-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0003_goalsuggestionlog'),
        ('user_management', '0004_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalsuggestionlog',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.role'),
        ),
    ]
