# Generated by Django 5.0.6 on 2024-08-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
    ]
