# Generated by Django 5.0.6 on 2024-08-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0004_goalsuggestionlog_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
