# Generated by Django 5.0.6 on 2024-08-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0004_goal_goal_type_goal_impact_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
