# Generated by Django 5.0.6 on 2024-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal_task_management", "0005_goal_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
