# Generated by Django 5.0.9 on 2024-09-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "goal_task_management",
            "0006_alter_subtask_created_at_alter_subtask_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="habit",
        ),
    ]
