# Generated by Django 5.0.6 on 2024-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goal_task_management', '0007_remove_goal_user_goal_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('short_term', 'Short-term'), ('long_term', 'Long-term')],
                                   default='not predefined'),
            preserve_default=False,
        ),
    ]
