# Generated by Django 5.0.6 on 2024-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goal_task_management', '0008_alter_goal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(max_length=255),
        ),
    ]
