# Generated by Django 5.0.6 on 2024-08-13 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('goal_task_management', '0009_alter_goal_goal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='is_predefined',
            new_name='is_custom',
        ),
    ]
