# Generated by Django 5.0.6 on 2024-08-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0010_rename_is_predefined_goal_is_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
