# Generated by Django 5.0.6 on 2024-08-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goal_task_management', '0011_alter_subtask_completed_at_alter_task_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
