# Generated by Django 5.0.6 on 2024-08-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0012_alter_goal_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='user_role',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='sub_category',
        ),
    ]
