# Generated by Django 5.0.6 on 2024-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0013_rename_user_role_goal_role_remove_goal_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
