# Generated by Django 5.0.6 on 2024-08-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goal_task_management', '0014_alter_goal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('short_term', 'Short-term'), ('long_term', 'Long-term')]),
        ),
    ]
