# Generated by Django 5.0.6 on 2024-08-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goal_task_management', '0015_alter_goal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('short_term', 'Short-term'), ('long_term', 'Long-term')]),
        ),
    ]
