# Generated by Django 5.0.6 on 2024-08-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0011_alter_category_name'),
        ('goal_task_management', '0016_alter_goal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ManyToManyField(related_name='goals', to='category_management.category'),
        ),
    ]
