# Generated by Django 5.0.6 on 2024-08-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0011_alter_category_name'),
        ('goal_task_management', '0017_goal_category'),
        ('user_management', '0038_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='goals', to='category_management.category'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('short_term', 'Short-term'), ('long_term', 'Long-term')], null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, related_name='goals', to='user_management.role'),
        ),
    ]
