# Generated by Django 5.0.6 on 2024-08-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task_management', '0018_alter_goal_category_alter_goal_goal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_custom',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
