# Generated by Django 5.0.6 on 2024-08-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0011_alter_category_name'),
        ('goal_task_management', '0019_alter_goal_is_custom'),
        ('user_management', '0038_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ManyToManyField(related_name='goals', to='category_management.category'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='role',
            field=models.ManyToManyField(related_name='goals', to='user_management.role'),
        ),
    ]
