# Generated by Django 5.0.9 on 2024-10-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task', '0004_goal_created_at_goal_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created_by',
        ),
    ]
