# Generated by Django 5.0 on 2024-11-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task', '0006_remove_goal_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('short_term', 'Short-term'), ('long_term', 'Long-term')], default='N/A'),
        ),
    ]
