# Generated by Django 5.0 on 2024-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task', '0007_alter_goal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.CharField(default='OpenAI'),
        ),
    ]
