# Generated by Django 5.0 on 2024-11-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task', '0008_goal_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='impact_score',
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
