# Generated by Django 5.0 on 2024-11-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task', '0009_remove_goal_impact_score_alter_goal_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created_by',
        ),
    ]
