# Generated by Django 5.0 on 2024-11-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task', '0010_remove_goal_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
