# Generated by Django 5.0 on 2024-11-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_task', '0011_goal_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
