# Generated by Django 5.0.6 on 2024-09-17 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journey", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjourneystatus",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_statuses",
                to="user_management.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userjourneystepstatus",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_statuses",
                to="journey.journeystep",
            ),
        ),
        migrations.AddField(
            model_name="userjourneystepstatus",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_statuses",
                to="user_management.userprofile",
            ),
        ),
    ]
