# Generated by Django 5.0.6 on 2024-08-18 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('journey', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronboardingstatus',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='useronboardingstatus',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='OnboardingStep',
        ),
        migrations.DeleteModel(
            name='UserOnboardingStatus',
        ),
    ]
