# Generated by Django 5.0.6 on 2024-09-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='start_date',
        ),
    ]
