# Generated by Django 5.0.9 on 2024-09-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystep',
            name='step_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
