# Generated by Django 5.0.6 on 2024-08-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('journey', '0003_remove_useronboardingstatus_current_step_and_more'),
        ('user_management', '0032_remove_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps',
                                              to='journey.journey')),
            ],
        ),
        migrations.CreateModel(
            name='UserJourneyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('current_step',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journeystep')),
                ('user_profile',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_statuses',
                                   to='user_management.userprofile')),
            ],
        ),
    ]
