# Generated by Django 5.0.9 on 2024-09-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_journeystep_step_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='journey_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
