# Generated by Django 5.0.9 on 2024-09-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_journeystep_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journeystep',
            unique_together={('journey', 'step_number')},
        ),
    ]
