# Generated by Django 5.0.6 on 2024-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_journeystep_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userjourneystatus',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
