# Generated by Django 5.0.6 on 2024-09-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_journeystep_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userjourneystatus',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
