# Generated by Django 5.0.9 on 2024-09-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_alter_journeystep_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjourneystatus',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey'),
        ),
    ]
