# Generated by Django 5.0.9 on 2024-09-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_alter_userjourneystatus_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjourneystatus',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='journey.journey'),
        ),
    ]
