# Generated by Django 5.0.6 on 2024-09-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0008_userjourneystepstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjourneystatus',
            name='paused',
        ),
    ]
