# Generated by Django 5.0.9 on 2024-09-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0009_remove_userjourneystatus_ended_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['journey_number']},
        ),
        migrations.AlterField(
            model_name='journey',
            name='journey_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='step_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
