# Generated by Django 5.0.6 on 2024-09-05 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0009_remove_userjourneystatus_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeystep',
            old_name='end_date',
            new_name='started_at',
        ),
        migrations.RenameField(
            model_name='userjourneystatus',
            old_name='end_date',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='journeystep',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='userjourneystatus',
            name='start_date',
        ),
        migrations.AddField(
            model_name='journeystep',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userjourneystatus',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userjourneystepstatus',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userjourneystepstatus',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userjourneystepstatus',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
