# Generated by Django 5.0.9 on 2024-09-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0010_alter_journey_options_alter_journey_journey_number_and_more'),
        ('user_management', '0004_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userjourneystatus',
            unique_together={('user_profile', 'journey')},
        ),
    ]
