# Generated by Django 5.0.6 on 2024-09-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journey", "0010_rename_end_date_journeystep_started_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journeystep",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="journeystep",
            name="started_at",
        ),
    ]
