# Generated by Django 5.0.6 on 2024-09-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journey", "0011_remove_journeystep_ended_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userjourneystepstatus",
            name="ended_at",
        ),
    ]
