# Generated by Django 5.0.9 on 2024-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0011_alter_userjourneystatus_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjourneystatus',
            name='completed_steps',
            field=models.IntegerField(default=0),
        ),
    ]
