# Generated by Django 5.0.9 on 2024-10-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0012_userjourneystatus_completed_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjourneystatus',
            name='progress',
        ),
    ]
