# Generated by Django 5.0.6 on 2024-09-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0012_remove_userjourneystepstatus_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjourneystepstatus',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_statuses', to='journey.journeystep'),
        ),
    ]
