# Generated by Django 5.0.9 on 2024-10-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0013_remove_userjourneystatus_progress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journeystep',
            unique_together=set(),
        ),
    ]
