# Generated by Django 5.0.9 on 2024-10-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0014_alter_journeystep_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='journeystep',
            unique_together={('journey', 'step_number')},
        ),
    ]
