# Generated by Django 5.0.9 on 2024-10-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0015_alter_journeystep_step_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userjourneystatus',
            options={'ordering': ['journey']},
        ),
    ]
