# Generated by Django 5.0.9 on 2024-10-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0016_alter_userjourneystatus_options'),
        ('user_management', '0020_alter_userprofile_custom_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userjourneystatus',
            unique_together={('journey', 'is_completed'), ('user_profile', 'journey')},
        ),
    ]
