# Generated by Django 5.0.9 on 2024-10-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0018_alter_userjourneystatus_unique_together'),
        ('user_management', '0020_alter_userprofile_custom_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userjourneystatus',
            unique_together={('user_profile', 'is_completed', 'journey'), ('user_profile', 'journey')},
        ),
    ]
