# Generated by Django 5.0.6 on 2024-08-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorycompletion',
            old_name='main_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categoryprogress',
            old_name='main_category',
            new_name='category',
        ),
    ]
