# Generated by Django 5.0.6 on 2024-08-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0003_alter_maincategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategorycompletion',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategorycompletion',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
