# Generated by Django 5.0.6 on 2024-08-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('category_management', '0005_alter_usercategoryprogress_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategorycompletion',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subcategorycompletion',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
