# Generated by Django 5.0.6 on 2024-08-14 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('category_management', '0006_alter_maincategorycompletion_completed_at_and_more'),
        ('goal_task_management', '0013_rename_user_role_goal_role_remove_goal_sub_category'),
        ('habit_management', '0009_remove_habit_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorycompletion',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='usercategoryprogress',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='subcategorycompletion',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='SubCategoryCompletion',
        ),
    ]
