# Generated by Django 5.0.6 on 2024-08-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('category_management', '0007_remove_subcategorycompletion_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(
                choices=[('Relationship', 'Relationship'), ('Health', 'Health'), ('Mindfulness', 'Mindfulness'),
                         ('Intellectual', 'Intellectual')]),
        ),
    ]
