# Generated by Django 5.0.6 on 2024-08-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0008_alter_maincategory_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCategory',
            new_name='Category',
        ),
    ]
