# Generated by Django 5.0.6 on 2024-08-19 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0009_rename_maincategory_category'),
        ('user_management', '0032_remove_userprofile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCategoryCompletion',
            new_name='CategoryCompletion',
        ),
        migrations.RenameModel(
            old_name='UserCategoryProgress',
            new_name='CategoryProgress',
        ),
    ]
