# Generated by Django 5.0.6 on 2024-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0010_rename_maincategorycompletion_categorycompletion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(),
        ),
    ]
