# Generated by Django 5.0.6 on 2024-08-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0011_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
