# Generated by Django 5.0.6 on 2024-08-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0012_rename_name_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
