# Generated by Django 5.0.9 on 2024-10-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('principle', '0002_initial'),
        ('user_management', '0030_alter_userprofile_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.userprofile'),
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50, unique=True)),
                ('principle', models.ManyToManyField(related_name='characters', to='principle.principle')),
            ],
        ),
    ]
