# Generated by Django 5.0.9 on 2024-10-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('principle', '0004_rolemodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodel',
            name='description',
            field=models.TextField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
