# Generated by Django 5.0.9 on 2024-10-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('principle', '0005_rolemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='character_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
