# Generated by Django 5.0.9 on 2024-10-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle', '0007_alter_rolemodel_character_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='principle',
            field=models.ManyToManyField(related_name='rolemodels', to='principle.principle'),
        ),
    ]
