# Generated by Django 5.0.9 on 2024-10-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_management', '0003_alter_principle_created_by_rolemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodel',
            name='gender',
            field=models.CharField(choices=[('Mail', 'Mail'), ('Femail', 'Femail')], default='none'),
            preserve_default=False,
        ),
    ]
