# Generated by Django 5.0.9 on 2024-10-09 20:05

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principle_management', '0006_alter_rolemodel_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='character_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='rolemodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['character_name'], name='rolemodel_name_trigram', opclasses=['gin_trgm_ops']),
        ),
    ]
