# Generated by Django 5.0.6 on 2024-08-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_sphere', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='life_sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='life_sphere.lifesphere'),
        ),
    ]
