# Generated by Django 5.0.9 on 2024-10-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_sphere', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LifeSphereCompletion',
        ),
    ]
