# Generated by Django 5.0.6 on 2024-08-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life_sphere", "0003_alter_area_life_sphere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="life_sphere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="life_sphere.lifesphere",
            ),
        ),
    ]
