# Generated by Django 5.0.9 on 2024-10-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_sphere', '0003_delete_lifespherecompletion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LifeSphereProgress',
        ),
    ]
