# Generated by Django 5.0.6 on 2024-08-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life_sphere', '0004_alter_area_life_sphere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
    ]
