# Generated by Django 5.0.6 on 2024-08-28 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('life_sphere', '0005_alter_area_options'),
        ('user_management', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('life_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='life_sphere.lifesphere')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(2, 'Strongly Agree'), (1, 'Agree'), (-1, 'Disagree'), (-2, 'Strongly Disagree')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='onboarding.onboardingquestion')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='user_management.userprofile')),
            ],
        ),
    ]
