# Generated by Django 5.0.6 on 2024-09-17 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("life_sphere", "0002_initial"),
        ("onboarding", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingprogress",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="onboardingquestion",
            name="life_sphere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="life_sphere.lifesphere",
            ),
        ),
        migrations.AddField(
            model_name="onboardingquestion",
            name="triggering_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="triggered_questions",
                to="onboarding.answeroption",
            ),
        ),
        migrations.AddField(
            model_name="onboardingprogress",
            name="completed_questions",
            field=models.ManyToManyField(
                related_name="completed_by_users", to="onboarding.onboardingquestion"
            ),
        ),
        migrations.AddField(
            model_name="onboardingprogress",
            name="skipped_questions",
            field=models.ManyToManyField(
                related_name="skipped_by_users", to="onboarding.onboardingquestion"
            ),
        ),
        migrations.AddField(
            model_name="answeroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="onboarding.onboardingquestion",
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.onboardingquestion",
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="user_answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.answeroption",
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="user_management.userprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userresponse",
            unique_together={("user_profile", "question")},
        ),
    ]
