# Generated by Django 5.0.6 on 2024-08-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_sphere', '0005_alter_area_options'),
        ('onboarding', '0002_alter_onboardingresponse_response'),
        ('user_management', '0006_remove_userbalance_user_userbalance_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingresponse',
            name='response',
            field=models.IntegerField(choices=[(10, 'Strongly Agree'), (5, 'Agree'), (-5, 'Disagree'), (-10, 'Strongly Disagree'), (0, "I don't know")]),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_questions', models.ManyToManyField(related_name='completed_by_users', to='onboarding.onboardingquestion')),
                ('current_life_sphere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='life_sphere.lifesphere')),
                ('skipped_questions', models.ManyToManyField(related_name='skipped_by_users', to='onboarding.onboardingquestion')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile')),
            ],
        ),
    ]
