# Generated by Django 5.0.9 on 2024-09-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='current_life_sphere',
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='skipped_questions',
        ),
    ]
