# Generated by Django 5.0.9 on 2024-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_remove_onboardingprogress_current_life_sphere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='completed_questions',
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='completed_questions',
            field=models.IntegerField(default=0),
        ),
    ]
