# Generated by Django 5.0.9 on 2024-10-04 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_sphere', '0004_delete_lifesphereprogress'),
        ('onboarding', '0004_remove_onboardingprogress_completed_questions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingquestion',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='onboardingquestion',
            name='is_followup',
        ),
        migrations.RemoveField(
            model_name='onboardingquestion',
            name='triggering_options',
        ),
        migrations.AddField(
            model_name='answeroption',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question_options', to='onboarding.onboardingquestion'),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='life_sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_questions', to='life_sphere.lifesphere'),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
