# Generated by Django 5.0.9 on 2024-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_rename_userprogress_onboardingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprogress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
