# Generated by Django 5.0.9 on 2024-09-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_onboardingprogress_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='text',
            new_name='option',
        ),
    ]
