# Generated by Django 5.0.9 on 2024-10-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_onboardingquestion_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeroption',
            old_name='next_question',
            new_name='tailored_question',
        ),
    ]
