# Generated by Django 5.0.9 on 2024-10-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_rename_next_question_answeroption_tailored_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresponse',
            options={'ordering': ['-timestamp']},
        ),
    ]
