# Generated by Django 5.0.9 on 2024-09-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_rename_text_questionoption_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionOption',
            new_name='ResponseOption',
        ),
    ]
