# Generated by Django 5.0.9 on 2024-10-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_alter_userresponse_options'),
        ('user_management', '0023_remove_userprofile_ai_assistant_model_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user_profile', 'question', 'user_answer')},
        ),
    ]
