# Generated by Django 5.0.9 on 2024-09-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0008_rename_questionoption_responseoption"),
        ("user_management", "0010_alter_userprofile_birth_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OnboardingResponse",
            new_name="OnboardingUserResponse",
        ),
    ]
