# Generated by Django 5.0.9 on 2024-09-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_rename_onboardingresponse_onboardinguserresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseOption',
            new_name='AnswerOption',
        ),
    ]
