# Generated by Django 5.0.9 on 2024-10-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_alter_userresponse_unique_together'),
        ('user_management', '0023_remove_userprofile_ai_assistant_model_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user_profile', 'question')},
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingquestion'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onboarding.answeroption'),
        ),
    ]
