# Generated by Django 5.0.9 on 2024-10-09 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_alter_userresponse_question_and_more'),
        ('user_management', '0030_alter_userprofile_age_range'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_responses', to='onboarding.onboardingquestion'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_responses', to='onboarding.answeroption'),
        ),
        migrations.AddConstraint(
            model_name='userresponse',
            constraint=models.UniqueConstraint(fields=('user_profile', 'question'), name='unique_user_question'),
        ),
    ]
