# Generated by Django 5.0.9 on 2024-10-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_alter_userresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
