# Generated by Django 5.0.9 on 2024-10-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_onboardingprogress_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnboardingProgress',
        ),
    ]
