# Generated by Django 5.0.9 on 2024-09-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_rename_onboardinganswer_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
