# Generated by Django 5.0.9 on 2024-09-13 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0015_onboardingquestion_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
