# Generated by Django 5.0.9 on 2024-09-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_onboardingquestion_triggering_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeroption',
            old_name='option',
            new_name='answer',
        ),
    ]
