# Generated by Django 5.0.9 on 2024-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0018_rename_option_answeroption_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='answer_code',
            field=models.IntegerField(default=0),
        ),
    ]
