# Generated by Django 5.0.9 on 2024-09-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0019_answeroption_answer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='answer_code',
        ),
    ]
