# Generated by Django 5.0.6 on 2024-08-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('frequency', models.JSONField(blank=True, default=dict, null=True)),
                ('is_predefined', models.BooleanField(default=False)),
            ],
        ),
    ]
