# Generated by Django 5.0.7 on 2024-08-04 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('habit_management', '0003_alter_habit_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_date',
        ),
    ]
