# Generated by Django 5.0.7 on 2024-08-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_management', '0004_remove_habit_end_date_remove_habit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='test_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
