# Generated by Django 5.0.7 on 2024-08-04 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('habit_management', '0006_alter_habit_frequency_alter_habit_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='test_field',
        ),
    ]
