# Generated by Django 5.0.6 on 2024-08-07 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_management', '0007_remove_habit_test_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='unique_habit_per_user',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_predefined',
            field=models.BooleanField(default=False),
        ),
    ]
