# Generated by Django 5.0.6 on 2024-08-14 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('habit_management', '0008_remove_habit_unique_habit_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='sub_category',
        ),
    ]
