name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the build
  pull_request:
    branches:
      - main  # Also triggers the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image (web and postgres tags)
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            andrewocean/mission_app:web
            andrewocean/mission_app:postgres

      # Step 5 (Optional): Clean up Docker resources
      - name: Clean up Docker images
        run: docker system prune -f